/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-03-14 07:38:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chatRoomList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/development/chat/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/simplechat/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603612617385L));
    _jspx_dependants.put("/WEB-INF/views/include/INCLUDE_HEAD.jsp", Long.valueOf(1609997362906L));
    _jspx_dependants.put("jar:file:/D:/development/chat/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/simplechat/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/development/chat/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/simplechat/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("\r\n");
      out.write("<!-- jstl -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- WEB CSS -->\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\">\r\n");
      out.write("\r\n");
      out.write("<!--  WEB JS -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/c4e734c793.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.1.5/sockjs.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/chat/list.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/chat/room.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/chat/modal.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 날짜 계산 -->\r\n");
      out.write("\r\n");
      //  fmt:formatDate
      org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
      boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
      try {
        _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fformatDate_005f0.setParent(null);
        // /WEB-INF/views/chat/chatRoomList.jsp(25,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setVar("today");
        // /WEB-INF/views/chat/chatRoomList.jsp(25,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setValue(new java.util.Date());
        // /WEB-INF/views/chat/chatRoomList.jsp(25,0) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyyMMdd");
        int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
        if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
        _jspx_th_fmt_005fformatDate_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"list-wrap br4 shadow\">\r\n");
      out.write("        <div class=\"flex\" style=\"width: 100%; height: 100%;\">\r\n");
      out.write("            <div class=\"list-left flex-column flex flex-justify \">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"icon-wrap\">\r\n");
      out.write("                            <i class=\"fas fa-comment icon\" name=\"chat-list\" onclick=\"roomCodeCheck(prompt('입장할 방의 코드를 입력하세요.'))\"></i>\r\n");
      out.write("                            <span class=\"icon-pop-text\">채팅</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-wrap\">\r\n");
      out.write("                            <i class=\"fas fa-comment-medical icon\" name=\"chat-list\" onclick=\"modalCreate()\"></i>\r\n");
      out.write("                            <span class=\"icon-pop-text\">채팅방 생성</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"icon-wrap\">\r\n");
      out.write("                            <i class=\"fas fa-cog icon\" name=\"setting\" onclick=\"modalSetting()\"></i>\r\n");
      out.write("                            <span class=\"icon-pop-text\">설정</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-wrap\">\r\n");
      out.write("                            <i class=\"fas fa-sign-out-alt icon\" name=\"logout-icon\" onclick=\"logout(confirm('정말 로그아웃 하시겠습니까?'))\"></i>\r\n");
      out.write("                            <span class=\"icon-pop-text\">로그아웃</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"list-right\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <!-- 최상단 -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list-top\">\r\n");
      out.write("                            <i class=\"fas fa-cloud-moon\" style=\"font-size: 24px;\"></i>\r\n");
      out.write("                            <h1 class=\"raleway\" style=\"font-size: 34px; font-weight: 700;\">\r\n");
      out.write("                                PHY\r\n");
      out.write("                            </h1>\r\n");
      out.write("                            <h3 class=\"roboto\" style=\"font-size: 18px;\">Chat</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"list-main\">\r\n");
      out.write("                    \t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 모달창 - 채팅방 입장 -->\r\n");
      out.write("    <div class=\"modal\" id=\"modal-join\" onclick=\"modalJoin()\"> \r\n");
      out.write("        <div class=\"modal-box\">\r\n");
      out.write("            <div class=\"room-register shadow\" onclick=\"noBubbling(event)\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"modal-close\">\r\n");
      out.write("                            <span onclick=\"modalJoin()\">X</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"list-top\" style=\"margin: 0 60px;\">\r\n");
      out.write("                            <h2 class=\"modal-title\" style=\"font-size: 20px;\">채팅방 입장</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <form id=\"join-form\" method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chatRoom/in\" autocomplete=\"off\">\r\n");
      out.write("                        <div class=\"input-box\">\r\n");
      out.write("                        \t<input type=\"hidden\" name=\"mem_id\" id=\"mem_id\" maxlength=\"20\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <div class=\"flex\" style=\"align-items: center;\">\r\n");
      out.write("                                <input type=\"text\" name=\"room_code\" id=\"room_code\" placeholder=\"채팅방 코드\" maxlength=\"20\"/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"flex\" id=\"join-pwd\" style=\"align-items: center; display: none;\">\r\n");
      out.write("                                <input type=\"text\" name=\"room_pwd\" id=\"room_pwd\" placeholder=\"채팅방 비밀번호\" maxlength=\"20\" />\r\n");
      out.write("                                <button type=\"button\" class=\"btn-normal-v m5\" onclick=\"roomPwdCheck(this)\">비밀번호확인</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" name=\"room_title\" id=\"room_title\" readonly placeholder=\"채팅방 이름\" maxlength=\"20\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"\" id=\"\" readonly placeholder=\"채팅방 정보\" maxlength=\"30\"/>\r\n");
      out.write("                            <div class=\"flex\" style=\"justify-content: flex-end; margin-top: 20px; margin-right: 80px;\">\r\n");
      out.write("                                <button type=\"submit\" id=\"join-btn\" class=\"btn-on m5\">입장</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-off m5\" onclick=\"modalJoin()\">취소</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 모달창 - 채팅방 생성 -->\r\n");
      out.write("    <div class=\"modal\" id=\"modal-create\" onclick=\"modalCreate()\"> \r\n");
      out.write("        <div class=\"modal-box\">\r\n");
      out.write("            <div class=\"room-register shadow\" onclick=\"noBubbling(event)\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"modal-close\">\r\n");
      out.write("                            <span onclick=\"modalCreate()\">X</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"list-top\" style=\"margin: 0 60px;\">\r\n");
      out.write("                            <h2 class=\"modal-title\" style=\"font-size: 20px;\">채팅방 생성</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <form id=\"frm\" method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chatRoom/create\" autocomplete=\"off\">\r\n");
      out.write("                        <div class=\"input-box\">\r\n");
      out.write("                        \t<input type=\"hidden\" name=\"host_id\" id=\"host_id\" maxlength=\"20\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"room_title\" id=\"room_title\" placeholder=\"채팅방 이름\" maxlength=\"20\"/>\r\n");
      out.write("                            <div class=\"flex\" style=\"align-items: center;\">\r\n");
      out.write("                                <input type=\"text\" name=\"room_pwd\" id=\"room_pwd\" class=\"off\" placeholder=\"채팅방 비밀번호\" disabled maxlength=\"20\"/>\r\n");
      out.write("                                <input type=\"checkbox\" class=\"m5\" onchange=\"pwd_on(this)\"/>비밀방\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"flex\" style=\"align-items: center;\">\r\n");
      out.write("                                <input type=\"text\" name=\"room_code\" id=\"room_code\" class=\"off\" readonly placeholder=\"채팅방 코드\"   maxlength=\"20\"/>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-normal-v m5\" onclick=\"getRoomCode(this)\">코드 생성</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" name=\"room_info\" id=\"room_info\" placeholder=\"채팅방 정보\" maxlength=\"30\"/>\r\n");
      out.write("                            <div class=\"flex\" style=\"justify-content: flex-end; margin-top: 20px; margin-right: 80px;\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn-on m5\">생성</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-off m5\" onclick=\"modalCreate()\">취소</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 모달창 - 계정설정 -->\r\n");
      out.write("    <div class=\"modal\" id=\"modal-setting\" onclick=\"modalSetting()\"> \r\n");
      out.write("        <div class=\"modal-box\">\r\n");
      out.write("            <div class=\"room-register shadow\" onclick=\"noBubbling(event)\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"modal-close\">\r\n");
      out.write("                            <span onclick=\"modalSetting()\">X</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"list-top\" style=\"margin: 0 60px;\">\r\n");
      out.write("                            <h2 class=\"modal-title\" style=\"font-size: 20px;\">계정 설정</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <form id=\"upMember\" method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/upMember\" autocomplete=\"off\">\r\n");
      out.write("                        <div class=\"input-box\">\r\n");
      out.write("                        \t<input type=\"text\" name=\"mem_id\" id=\"mem_id\" placeholder=\"아이디\" maxlength=\"20\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"mem_num\" id=\"mem_num\" placeholder=\"아이디\" maxlength=\"20\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mem_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"mem_pwd\" id=\"mem_pwd\" placeholder=\"비밀번호\" maxlength=\"20\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mem_pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"mem_name\" id=\"mem_name\" placeholder=\"이름\" maxlength=\"20\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"mem_buseo\" id=\"mem_buseo\" placeholder=\"부서\" maxlength=\"4\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mem_buseo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"mem_grade\" id=\"mem_grade\" placeholder=\"직급\" maxlength=\"4\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mem_grade}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"mem_auth\" id=\"mem_auth\" placeholder=\"권한\" maxlength=\"4\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mem_auth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                            <div class=\"flex\" style=\"justify-content: flex-end; margin-top: 20px; margin-right: 80px;\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn-on m5\">수정</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-off m5\" onclick=\"modalSetting()\">취소</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 모달창 - 방 설정 -->\r\n");
      out.write("    <div class=\"modal\" id=\"modal-room-setting\" onclick=\"modalRoomSetting()\"> \r\n");
      out.write("        <div class=\"modal-box\">\r\n");
      out.write("            <div class=\"room-register shadow\" onclick=\"noBubbling(event)\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"modal-close\">\r\n");
      out.write("                            <span onclick=\"modalRoomSetting()\">X</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"list-top\" style=\"margin: 0 60px;\">\r\n");
      out.write("                            <h2 class=\"modal-title\" style=\"font-size: 20px;\">프로필 설정</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <form id=\"frm\" method=\"POST\" action=\"\" autocomplete=\"off\">\r\n");
      out.write("                        <div class=\"input-box\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"room_title\" id=\"room_title\" placeholder=\"방 제목\" maxlength=\"20\" value=\"title\"/>\r\n");
      out.write("                            <div class=\"flex\" style=\"align-items: center;\">\r\n");
      out.write("                                <input type=\"text\" name=\"room_code\" id=\"room_code\" class=\"off\" readonly placeholder=\"채팅방 코드\" value=\"code\"  maxlength=\"20\"/>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-normal-v m5\" onclick=\"getRoomCode(this)\">코드 생성</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"flex\" style=\"align-items: center;\">\r\n");
      out.write("                                <input type=\"text\" name=\"room_pwd\" id=\"room_pwd\" class=\"off\" placeholder=\"채팅방 비밀번호\" value=\"pwd\" disabled maxlength=\"20\"/>\r\n");
      out.write("                                <input type=\"checkbox\" class=\"m5\" onchange=\"pwd_on(this)\"/>비밀방\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" name=\"host_id\" id=\"host_id\" placeholder=\"호스트\" maxlength=\"4\"/>\r\n");
      out.write("                            <input type=\"text\" name=\"room_info\" id=\"room_info\" placeholder=\"방 정보\" maxlength=\"4\"/>\r\n");
      out.write("                            <div class=\"flex\" style=\"justify-content: flex-end; margin-top: 20px; margin-right: 80px;\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn-on m5\">수정</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-off m5\" onclick=\"modalRoomSetting()\">취소</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //모달창-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 채팅방 -->\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t<!-- //채팅방 -->\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/modal.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\tfunction chatScrollBottom() {\r\n");
      out.write("\t    $(\".chat-main\").scrollTop($(\".chat-main\")[0].scrollHeight);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getRoomCode(btn) {\r\n");
      out.write("\t    $(btn).siblings(\"#room_code\").val(Math.random().toString(36).substr(2,11));\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    function numberCircleZero() {\r\n");
      out.write("\r\n");
      out.write("        var circle = $(\".numberCircle span\");\r\n");
      out.write("\r\n");
      out.write("        for (let i = 0; i < circle.length; i++) {\r\n");
      out.write("            if ( $(circle[i]).html() == '') {\r\n");
      out.write("                $( circle[i] ).parent(\".numberCircle\").hide();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function noBubbling(event) {\r\n");
      out.write("        event.stopPropagation();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function getRoomCode(btn) {\r\n");
      out.write("        $(btn).siblings(\"#room_code\").val(Math.random().toString(36).substr(2,11));\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function logout(params) {\r\n");
      out.write("        \r\n");
      out.write("        if (params) {\r\n");
      out.write("            location.replace('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function pwd_on(box) {\r\n");
      out.write("\r\n");
      out.write("        var room_pwd = $(box).siblings(\"#room_pwd\");\r\n");
      out.write("\r\n");
      out.write("        if ($(box).is(\":checked\")) {\r\n");
      out.write("            room_pwd.attr(\"disabled\", false);\r\n");
      out.write("        }else {\r\n");
      out.write("            room_pwd.attr(\"disabled\", true);\r\n");
      out.write("        }\r\n");
      out.write("        room_pwd.toggleClass(\"off\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("    numberCircleZero();\r\n");
      out.write("\r\n");
      out.write("    $(\".icon-wrap\").hover(function() {\r\n");
      out.write("        $(this).children(\".icon-pop-text\").toggle();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\"#upMember\").submit(function () {\r\n");
      out.write("        alert(\"정보 수정으로 인해 로그아웃 됩니다.\")\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\"#join-form\").submit(function (event) {\r\n");
      out.write("\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("        roomPwdCheck(this);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#chat-room-menu-icon\").click(function (event) {\r\n");
      out.write("        \r\n");
      out.write("        $(\".chat-room-menu\").toggle();\r\n");
      out.write("        event.stopPropagation();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(document).click(function(){\r\n");
      out.write("        $(\".chat-room-menu\").hide();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\".modal-box\").draggable();\r\n");
      out.write("    $(\".chat-wrap\").draggable();\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- ajax -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction roomCodeCheck(room_code) {\r\n");
      out.write("\t\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t\t\ttype \t: \"POST\",\r\n");
      out.write("\t        url \t: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chatRoom/roomCodeCheck\",\r\n");
      out.write("\t\t\tdata    : { room_code : room_code},\r\n");
      out.write("\t\t\tsuccess\t: function( result ) { \r\n");
      out.write("\t            \r\n");
      out.write("\t            if ( result.room_id != null) {\r\n");
      out.write("\t            \t\r\n");
      out.write("\t\t\t\t\talert(result.room_id);\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t                $(\"#join-form\").find(\"#room_code\").val(result.room_code);\r\n");
      out.write("                    $(\"#join-form\").find(\"#room_title\").val(result.room_title);\r\n");
      out.write("                    $(\"#join-form\").find(\"#room_info\").val(result.room_info);\r\n");
      out.write("                    \r\n");
      out.write("                    if (result.room_pwd != null ) {\r\n");
      out.write("                        $(\"#join-form\").find(\"#join-pwd\").show();\r\n");
      out.write("                        joinBtnToggle(false);\r\n");
      out.write("                    }else{\r\n");
      out.write("                        if ( $(\"#join-btn\").hasClass(\"btn-off\") ) joinBtnToggle(true);\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    modalJoin(true);\r\n");
      out.write("                    \r\n");
      out.write("\t            }else {\r\n");
      out.write("\t                alert(\"채팅방 코드가 틀렸습니다. 해당하는 방이 존재하지 않습니다\");\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror\t: function( event ) {\r\n");
      out.write("\t\t\t\talert(event);\r\n");
      out.write("\t            alert(\"error 관리자에게 문의 하십시오.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    function roomPwdCheck(btn) {\r\n");
      out.write("\r\n");
      out.write("        var frm = $(btn).parents(\"form\");\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("\t\t\ttype \t: \"POST\",\r\n");
      out.write("            url \t: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chatRoom/roomCodeCheck\",\r\n");
      out.write("            data    : { room_code   : frm.find(\"#room_code\").val(),\r\n");
      out.write("                        room_pwd    : frm.find(\"#room_pwd\").val() },\r\n");
      out.write("\t\t\tsuccess\t: function( result ) {   \r\n");
      out.write("                \r\n");
      out.write("                if ( result != null) {\r\n");
      out.write("                    joinBtnToggle(true);\r\n");
      out.write("                    frm.find(\"#join-pwd\").hide();\r\n");
      out.write("                }else {\r\n");
      out.write("                    alert(\"채팅방 비밀번호가 틀렸습니다.\");\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror\t: function() {\r\n");
      out.write("                alert(\"error 관리자에게 문의 하십시오.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\tvar mem_id = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t//let sock = new SockJS(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chat\");\r\n");
      out.write("\tlet sock = new SockJS(\"http://localhost:8080/simplechat/chat\");\r\n");
      out.write("\tsock.onmessage = onMessage;\r\n");
      out.write("\tsock.onclose = onClose;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction sendBtn(btn) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t    var sendData = { message : $(btn).siblings(\"textarea\").val(),\r\n");
      out.write("\t    \t\t\t\t mem_id\t : mem_id,\r\n");
      out.write("\t    \t\t\t\t room_id : $(btn).siblings(\"#room_id\").val() };\r\n");
      out.write("\t \tsendMessage(JSON.stringify(sendData));\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 메시지 전송\r\n");
      out.write("\tfunction sendMessage(data) {\r\n");
      out.write("\t\tsock.send(data);\r\n");
      out.write("\t}\r\n");
      out.write("\t// 서버로부터 메시지를 받았을 때\r\n");
      out.write("\tfunction onMessage(msg) {\r\n");
      out.write("\t\tvar data = msg.data;\r\n");
      out.write("\t    \r\n");
      out.write("\t    if(data != null && data.trim() != '') {\r\n");
      out.write("\t        var jsonData = JSON.parse(data);\r\n");
      out.write("\t        setChat(jsonData);\r\n");
      out.write("\t        \r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t// 서버와 연결을 끊었을 때\r\n");
      out.write("\tfunction onClose(evt) {\r\n");
      out.write("\t\t$(\"#messageArea\").append(\"연결 끊김\");\r\n");
      out.write("\t    //로그아웃\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setChat(jsonData) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar chat;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif ( mem_id == jsonData.mem_id ) {\r\n");
      out.write("\t\t\t//본인 채팅일 경우\r\n");
      out.write("\t\t\tchat = '<div class=\"chat-container my-chat\">';\r\n");
      out.write("\t\t\t\tchat += '<div class=\"chat-icon\">';\r\n");
      out.write("\t\t\t\t\tchat += '<img src=\"images/free-icon-human-106137.png\" alt=\"\">';\r\n");
      out.write("\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\tchat += '<div class=\"chat\">';\r\n");
      out.write("\t\t\t\t\tchat += '<div class=\"chat-name\">';\r\n");
      out.write("\t\t\t\t\t\tchat += '<h4>자신</h4>';\r\n");
      out.write("\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\tchat += '<div class=\"chat-content\">';\r\n");
      out.write("\t\t\t\t\tchat += '<div class=\"chat-text\">';\r\n");
      out.write("\t\t\t\t\t\tchat += '<span>' + jsonData.chat + '</span>';\r\n");
      out.write("\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\t\tchat += '<div class=\"chat-info\">';\r\n");
      out.write("\t\t\t\t\t\tchat += '<span class=\"chat-count\">1</span>';\r\n");
      out.write("\t\t\t\t\t\tchat += '<span class=\"chat-time\">' + jsonData.chat_time + '</span>';\r\n");
      out.write("\t\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\tchat += '</div>';\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tchat = '<div class=\"chat-container\">';\r\n");
      out.write("\t\t\t\tchat += '<div class=\"chat-icon\">';\r\n");
      out.write("\t\t\t\t\tchat += '<img src=\"images/free-icon-human-106137.png\" alt=\"\">';\r\n");
      out.write("\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\tchat += '<div class=\"chat\">';\r\n");
      out.write("\t\t\t\t\tchat += '<div class=\"chat-name\">';\r\n");
      out.write("\t\t\t\t\t\tchat += '<h4>' + jsonData.mem_num + '</h4>';\r\n");
      out.write("\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\tchat += '<div class=\"chat-content\">';\r\n");
      out.write("\t\t\t\t\tchat += '<div class=\"chat-text\">';\r\n");
      out.write("\t\t\t\t\t\tchat += '<span>' + jsonData.chat + '</span>';\r\n");
      out.write("\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\t\tchat += '<div class=\"chat-info\">';\r\n");
      out.write("\t\t\t\t\t\tchat += '<span class=\"chat-count\">1</span>';\r\n");
      out.write("\t\t\t\t\t\tchat += '<span class=\"chat-time\">' + jsonData.chat_time + '</span>';\r\n");
      out.write("\t\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\t\tchat += '</div>';\r\n");
      out.write("\t\t\tchat += '</div>';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#room\" + jsonData.room_id).html(chat);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/chat/chatRoomList.jsp(16,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem_id} == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<script type=\"text/javascript\">\r\n");
          out.write("\t\talert(\"aaa\");\r\n");
          out.write("\t</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                    \t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t                    \t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    \t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/chat/chatRoomList.jsp(73,22) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                    \t\t<div class=\"room-wrap flex\" class=\"room-wrap flex\">\r\n");
          out.write("\t                    \t\t\t<div class=\"room-info-wrap flex flex-column\">\r\n");
          out.write("\t                    \t\t\t\t<span>입장한 채팅방이 없습니다.</span>\r\n");
          out.write("\t                    \t\t\t</div>\r\n");
          out.write("\t                    \t\t</div>\r\n");
          out.write("\t                    \t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                    \t\t <!-- 채팅방 목록 뜨는곳. -->\r\n");
          out.write("\t\t                    \t");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t                        <!-- //채팅방 목록 뜨는곳. -->\r\n");
          out.write("\t                    \t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/chat/chatRoomList.jsp(82,23) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("roomList");
      // /WEB-INF/views/chat/chatRoomList.jsp(82,23) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/chat/chatRoomList.jsp(82,23) '${roomList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${roomList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/chat/chatRoomList.jsp(82,23) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t                        <div class=\"room-wrap flex\" ondblclick=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/chatRoom/roomJoin?room_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.room_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t                            <div class=\"room-icon-wrap flex\">\r\n");
            out.write("\t\t\t                                <div class=\"room-icon\">\r\n");
            out.write("\t\t\t                                    <img class=\"pointer\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/images/free-icon-human-106137.png\" alt=\"\">\r\n");
            out.write("\t\t\t                                </div>\r\n");
            out.write("\t\t\t                            </div>\r\n");
            out.write("\t\t\t                            <div class=\"room-info-wrap flex flex-column\">\r\n");
            out.write("\t\t\t                                <div class=\"room-info\">\r\n");
            out.write("\t\t\t                                    <div style=\"width: 100%;\">\r\n");
            out.write("\t\t\t                                        <div class=\"room-info-title\">\r\n");
            out.write("\t\t\t                                            <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.room_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t                                        </div>\r\n");
            out.write("\t\t\t                                        <div class=\"room-info-lastchat\">\r\n");
            out.write("\t\t\t                                        \t<!-- 마지막으로 채팅 -->\r\n");
            out.write("\t\t\t                                            <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.lastChat.chat}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("\t\t\t                                        </div>\r\n");
            out.write("\t\t\t                                    </div>\r\n");
            out.write("\t\t\t                                </div>\r\n");
            out.write("\t\t\t                            </div>\r\n");
            out.write("\t\t\t                            <div class=\"room-alram flex flex-column\">\r\n");
            out.write("\t\t\t                                <div class=\"room-alram-time\">\r\n");
            out.write("\t\t\t                                \t<!-- 마지막 채팅 시간. -->\r\n");
            out.write("\t\t\t                                \t");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t                                </div>\r\n");
            out.write("\t\t\t                                <div class=\"room-alram-misscnt\">\r\n");
            out.write("\t\t\t                                    <span class=\"numberCircle \">\r\n");
            out.write("\t\t\t                                    \t<!-- 읽지 않는 채팅 수. -->\r\n");
            out.write("\t\t\t                                    \t<!-- <span>roomList.chatCount</span> -->\r\n");
            out.write("\t\t\t                                    \t<span>11</span>\r\n");
            out.write("\t\t\t                                    </span>\r\n");
            out.write("\t\t\t                                </div>\r\n");
            out.write("\t\t\t                            </div>\r\n");
            out.write("\t\t\t                        </div>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/chat/chatRoomList.jsp(105,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(" ${roomList.lastChat.chat_time} != null ", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t                                \t\t");
          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t                                \t\t");
          if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t                                \t\t");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t                                \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/chat/chatRoomList.jsp(106,37) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setVar("lastDay");
      // /WEB-INF/views/chat/chatRoomList.jsp(106,37) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.lastChat.chat_time}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/chat/chatRoomList.jsp(106,37) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyyMMdd");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/chat/chatRoomList.jsp(107,37) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("day");
      // /WEB-INF/views/chat/chatRoomList.jsp(107,37) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/chat/chatRoomList.jsp(107,37) '${today - lastDay }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${today - lastDay }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                                \t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/chat/chatRoomList.jsp(109,38) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(false);
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t\t");
          if (_jspx_meth_fmt_005fformatDate_005f2(_jspx_th_c_005fwhen_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t\t<span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lastDay}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t                                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      // /WEB-INF/views/chat/chatRoomList.jsp(110,39) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f2.setVar("lastDay");
      // /WEB-INF/views/chat/chatRoomList.jsp(110,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f2.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.lastChat.chat_time}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/chat/chatRoomList.jsp(110,39) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f2.setPattern("aa hh:mm");
      int _jspx_eval_fmt_005fformatDate_005f2 = _jspx_th_fmt_005fformatDate_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f2);
      _jspx_th_fmt_005fformatDate_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/chat/chatRoomList.jsp(113,38) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(false);
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t\t<span>어제</span>\r\n");
          out.write("\t\t\t\t                                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t\t");
          if (_jspx_meth_fmt_005fformatDate_005f3(_jspx_th_c_005fotherwise_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t                                \t\t\t<span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lastDay}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t                                \t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f1);
      // /WEB-INF/views/chat/chatRoomList.jsp(117,39) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f3.setVar("lastDay");
      // /WEB-INF/views/chat/chatRoomList.jsp(117,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f3.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.lastChat.chat_time}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/chat/chatRoomList.jsp(117,39) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f3.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f3 = _jspx_th_fmt_005fformatDate_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f3);
      _jspx_th_fmt_005fformatDate_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/chat/chatRoomList.jsp(304,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("roomList");
      // /WEB-INF/views/chat/chatRoomList.jsp(304,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/chat/chatRoomList.jsp(304,1) '${roomList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${roomList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/chat/chatRoomList.jsp(304,1) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<div class=\"chat-wrap br4 shadow flex flex-justify\">\r\n");
            out.write("\t        <div class=\"chat-box\">\r\n");
            out.write("\t            <div class=\"chat-top flex\">\r\n");
            out.write("\t                <div class=\"chat-room-icon m-t5\" style=\"width: 20%;\">\r\n");
            out.write("\t                    <div class=\"chat-icon\">\r\n");
            out.write("\t                        <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/images/free-icon-human-106137.png\" alt=\"\" onclick=\"\">\r\n");
            out.write("\t                    </div>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t                <div class=\"chat-title m-t10\" style=\"width: 70%;\">\r\n");
            out.write("\t                    <h3 class=\"chat-room-title\" name=\"chat-room-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.room_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t                <div class=\"chat-title\" style=\"width: 10%; \">\r\n");
            out.write("\t                    <div class=\"m-b5\" >\r\n");
            out.write("\t                        <i class=\"far fa-times-circle icon\" onclick=\"roomOpen()\"></i>\r\n");
            out.write("\t                    </div>\r\n");
            out.write("\t                    <div class=\"chat-room-menu-warp\">\r\n");
            out.write("\t                        <i class=\"fas fa-bars icon\" id=\"chat-room-menu-icon\"></i>\r\n");
            out.write("\t                        <ul class=\"chat-room-menu shadow-all2\">\r\n");
            out.write("\t                            <li>채팅방 초대</li>\r\n");
            out.write("\t                            <li onclick=\"modalSetting()\">채팅방 설정</li>\r\n");
            out.write("\t                            <li><hr class=\"m-tb5\" /></li>\r\n");
            out.write("\t                            <li onclick=\"roomExit(confirm('정말 나가시겠습니까?'))\">채팅방 나가기</li>\r\n");
            out.write("\t                        </ul>\r\n");
            out.write("\t                    </div>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t            <!-- 채팅 -->\r\n");
            out.write("\t            <div class=\"chat-main\" id=\"room");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.room_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t            <!-- //채팅 -->\r\n");
            out.write("\t            <div class=\"chat-bottom\">\r\n");
            out.write("\t                <div style=\"padding: 5px 5px;\">\r\n");
            out.write("\t                \t<input type=\"hidden\" name=\"room_id\" id=\"room_id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomList.room_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" }\" />\r\n");
            out.write("\t                    <textarea class=\"chat-send-text noto\" name=\"messges\" type=\"texta\" id=\"message\" autocomplete=\"off\" ></textarea>\r\n");
            out.write("\t                    <input type=\"button\" id=\"sendBtn\" class=\"chat-send-btn\" onclick=\"sendBtn(this)\" value=\"전송\" />\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t                <div>\r\n");
            out.write("\t                    <i class=\"far fa-smile-beam icon\"></i>\r\n");
            out.write("\t                    <i class=\"fas fa-paperclip icon\"></i>\r\n");
            out.write("\t                </div>\r\n");
            out.write("\t            </div>\r\n");
            out.write("\t        </div>\r\n");
            out.write("\t    </div>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
